
interface languageCodeObj {
  name: LanguageName;
  code: string;
}

export enum LanguageName {
  Afrikaans = 'Afrikaans',
  Arabic = 'Arabic',
  Armenian = 'Armenian',
  Azerbaijani = 'Azerbaijani',
  Belarusian = 'Belarusian',
  Bosnian = 'Bosnian',
  Bulgarian = 'Bulgarian',
  Catalan = 'Catalan',
  Chinese = 'Chinese',
  Croatian = 'Croatian',
  Czech = 'Czech',
  Danish = 'Danish',
  Dutch = 'Dutch',
  English = 'English',
  Estonian = 'Estonian',
  Finnish = 'Finnish',
  French = 'French',
  Galician = 'Galician',
  German = 'German',
  Greek = 'Greek',
  Hebrew = 'Hebrew',
  Hindi = 'Hindi',
  Hungarian = 'Hungarian',
  Icelandic = 'Icelandic',
  Indonesian = 'Indonesian',
  Italian = 'Italian',
  Japanese = 'Japanese',
  Kannada = 'Kannada',
  Kazakh = 'Kazakh',
  Korean = 'Korean',
  Latvian = 'Latvian',
  Lithuanian = 'Lithuanian',
  Macedonian = 'Macedonian',
  Malay = 'Malay',
  Marathi = 'Marathi',
  Maori = 'Maori',
  Nepali = 'Nepali',
  Norwegian = 'Norwegian',
  Persian = 'Persian',
  Polish = 'Polish',
  Portuguese = 'Portuguese',
  Romanian = 'Romanian',
  Russian = 'Russian',
  Serbian = 'Serbian',
  Slovak = 'Slovak',
  Slovenian = 'Slovenian',
  Spanish = 'Spanish',
  Swahili = 'Swahili',
  Swedish = 'Swedish',
  Tagalog = 'Tagalog',
  Tamil = 'Tamil',
  Thai = 'Thai',
  Turkish = 'Turkish',
  Ukrainian = 'Ukrainian',
  Urdu = 'Urdu',
  Vietnamese = 'Vietnamese',
  Welsh = 'Welsh'
}

export const languageCodeList: languageCodeObj[] = [
  { name: LanguageName.Afrikaans, code: '01' },
  { name: LanguageName.Arabic, code: '02' },
  { name: LanguageName.Armenian, code: '03' },
  { name: LanguageName.Azerbaijani, code: '04' },
  { name: LanguageName.Belarusian, code: '05' },
  { name: LanguageName.Bosnian, code: '06' },
  { name: LanguageName.Bulgarian, code: '07' },
  { name: LanguageName.Catalan, code: '08' },
  { name: LanguageName.Chinese, code: '09' },
  { name: LanguageName.Croatian, code: '10' },
  { name: LanguageName.Czech, code: '11' },
  { name: LanguageName.Danish, code: '12' },
  { name: LanguageName.Dutch, code: '13' },
  { name: LanguageName.English, code: '14' },
  { name: LanguageName.Estonian, code: '15' },
  { name: LanguageName.Finnish, code: '16' },
  { name: LanguageName.French, code: '17' },
  { name: LanguageName.Galician, code: '18' },
  { name: LanguageName.German, code: '19' },
  { name: LanguageName.Greek, code: '20' },
  { name: LanguageName.Hebrew, code: '21' },
  { name: LanguageName.Hindi, code: '22' },
  { name: LanguageName.Hungarian, code: '23' },
  { name: LanguageName.Icelandic, code: '24' },
  { name: LanguageName.Indonesian, code: '25' },
  { name: LanguageName.Italian, code: '26' },
  { name: LanguageName.Japanese, code: '27' },
  { name: LanguageName.Kannada, code: '28' },
  { name: LanguageName.Kazakh, code: '29' },
  { name: LanguageName.Korean, code: '30' },
  { name: LanguageName.Latvian, code: '31' },
  { name: LanguageName.Lithuanian, code: '32' },
  { name: LanguageName.Macedonian, code: '33' },
  { name: LanguageName.Malay, code: '34' },
  { name: LanguageName.Marathi, code: '35' },
  { name: LanguageName.Maori, code: '36' },
  { name: LanguageName.Nepali, code: '37' },
  { name: LanguageName.Norwegian, code: '38' },
  { name: LanguageName.Persian, code: '39' },
  { name: LanguageName.Polish, code: '40' },
  { name: LanguageName.Portuguese, code: '41' },
  { name: LanguageName.Romanian, code: '42' },
  { name: LanguageName.Russian, code: '43' },
  { name: LanguageName.Serbian, code: '44' },
  { name: LanguageName.Slovak, code: '45' },
  { name: LanguageName.Slovenian, code: '46' },
  { name: LanguageName.Spanish, code: '47' },
  { name: LanguageName.Swahili, code: '48' },
  { name: LanguageName.Swedish, code: '49' },
  { name: LanguageName.Tagalog, code: '50' },
  { name: LanguageName.Tamil, code: '51' },
  { name: LanguageName.Thai, code: '52' },
  { name: LanguageName.Turkish, code: '53' },
  { name: LanguageName.Ukrainian, code: '54' },
  { name: LanguageName.Urdu, code: '55' },
  { name: LanguageName.Vietnamese, code: '56' },
  { name: LanguageName.Welsh, code: '57' }
];