
interface languageCodeObj {
  name: LanguageName;
  code: string;
  isoCode: string;
}

export enum LanguageName {
  Afrikaans = 'Afrikaans',
  Arabic = 'Arabic',
  Armenian = 'Armenian',
  Azerbaijani = 'Azerbaijani',
  Belarusian = 'Belarusian',
  Bosnian = 'Bosnian',
  Bulgarian = 'Bulgarian',
  Catalan = 'Catalan',
  Chinese = 'Chinese',
  Croatian = 'Croatian',
  Czech = 'Czech',
  Danish = 'Danish',
  Dutch = 'Dutch',
  English = 'English',
  Estonian = 'Estonian',
  Finnish = 'Finnish',
  French = 'French',
  Galician = 'Galician',
  German = 'German',
  Greek = 'Greek',
  Hebrew = 'Hebrew',
  Hindi = 'Hindi',
  Hungarian = 'Hungarian',
  Icelandic = 'Icelandic',
  Indonesian = 'Indonesian',
  Italian = 'Italian',
  Japanese = 'Japanese',
  Kannada = 'Kannada',
  Kazakh = 'Kazakh',
  Korean = 'Korean',
  Latvian = 'Latvian',
  Lithuanian = 'Lithuanian',
  Macedonian = 'Macedonian',
  Malay = 'Malay',
  Marathi = 'Marathi',
  Maori = 'Maori',
  Nepali = 'Nepali',
  Norwegian = 'Norwegian',
  Persian = 'Persian',
  Polish = 'Polish',
  Portuguese = 'Portuguese',
  Romanian = 'Romanian',
  Russian = 'Russian',
  Serbian = 'Serbian',
  Slovak = 'Slovak',
  Slovenian = 'Slovenian',
  Spanish = 'Spanish',
  Swahili = 'Swahili',
  Swedish = 'Swedish',
  Tagalog = 'Tagalog',
  Tamil = 'Tamil',
  Thai = 'Thai',
  Turkish = 'Turkish',
  Ukrainian = 'Ukrainian',
  Urdu = 'Urdu',
  Vietnamese = 'Vietnamese',
  Welsh = 'Welsh'
}

export const languageCodeList: languageCodeObj[] = [
  { name: LanguageName.Afrikaans, code: '01', isoCode: 'af' },
  { name: LanguageName.Arabic, code: '02', isoCode: 'ar' },
  { name: LanguageName.Armenian, code: '03', isoCode: 'hy' },
  { name: LanguageName.Azerbaijani, code: '04', isoCode: 'az' },
  { name: LanguageName.Belarusian, code: '05', isoCode: 'be' },
  { name: LanguageName.Bosnian, code: '06', isoCode: 'bs' },
  { name: LanguageName.Bulgarian, code: '07', isoCode: 'bg' },
  { name: LanguageName.Catalan, code: '08', isoCode: 'ca' },
  { name: LanguageName.Chinese, code: '09', isoCode: 'zh' },
  { name: LanguageName.Croatian, code: '10', isoCode: 'hr' },
  { name: LanguageName.Czech, code: '11', isoCode: 'cs' },
  { name: LanguageName.Danish, code: '12', isoCode: 'da' },
  { name: LanguageName.Dutch, code: '13', isoCode: 'nl' },
  { name: LanguageName.English, code: '14', isoCode: 'en' },
  { name: LanguageName.Estonian, code: '15', isoCode: 'et' },
  { name: LanguageName.Finnish, code: '16', isoCode: 'fi' },
  { name: LanguageName.French, code: '17', isoCode: 'fr' },
  { name: LanguageName.Galician, code: '18', isoCode: 'gl' },
  { name: LanguageName.German, code: '19', isoCode: 'de' },
  { name: LanguageName.Greek, code: '20', isoCode: 'el' },
  { name: LanguageName.Hebrew, code: '21', isoCode: 'he' },
  { name: LanguageName.Hindi, code: '22', isoCode: 'hi' },
  { name: LanguageName.Hungarian, code: '23', isoCode: 'hu' },
  { name: LanguageName.Icelandic, code: '24', isoCode: 'is' },
  { name: LanguageName.Indonesian, code: '25', isoCode: 'id' },
  { name: LanguageName.Italian, code: '26', isoCode: 'it' },
  { name: LanguageName.Japanese, code: '27', isoCode: 'ja' },
  { name: LanguageName.Kannada, code: '28', isoCode: 'kn' },
  { name: LanguageName.Kazakh, code: '29', isoCode: 'kk' },
  { name: LanguageName.Korean, code: '30', isoCode: 'ko' },
  { name: LanguageName.Latvian, code: '31', isoCode: 'lv' },
  { name: LanguageName.Lithuanian, code: '32', isoCode: 'lt' },
  { name: LanguageName.Macedonian, code: '33', isoCode: 'mk' },
  { name: LanguageName.Malay, code: '34', isoCode: 'ms' },
  { name: LanguageName.Marathi, code: '35', isoCode: 'mr' },
  { name: LanguageName.Maori, code: '36', isoCode: 'mi' },
  { name: LanguageName.Nepali, code: '37', isoCode: 'ne' },
  { name: LanguageName.Norwegian, code: '38', isoCode: 'no' },
  { name: LanguageName.Persian, code: '39', isoCode: 'fa' },
  { name: LanguageName.Polish, code: '40', isoCode: 'pl' },
  { name: LanguageName.Portuguese, code: '41', isoCode: 'pt' },
  { name: LanguageName.Romanian, code: '42', isoCode: 'ro' },
  { name: LanguageName.Russian, code: '43', isoCode: 'ru' },
  { name: LanguageName.Serbian, code: '44', isoCode: 'sr' },
  { name: LanguageName.Slovak, code: '45', isoCode: 'sk' },
  { name: LanguageName.Slovenian, code: '46', isoCode: 'sl' },
  { name: LanguageName.Spanish, code: '47', isoCode: 'es' },
  { name: LanguageName.Swahili, code: '48', isoCode: 'sw' },
  { name: LanguageName.Swedish, code: '49', isoCode: 'sv' },
  { name: LanguageName.Tagalog, code: '50', isoCode: 'tl' },
  { name: LanguageName.Tamil, code: '51', isoCode: 'ta' },
  { name: LanguageName.Thai, code: '52', isoCode: 'th' },
  { name: LanguageName.Turkish, code: '53', isoCode: 'tr' },
  { name: LanguageName.Ukrainian, code: '54', isoCode: 'uk' },
  { name: LanguageName.Urdu, code: '55', isoCode: 'ur' },
  { name: LanguageName.Vietnamese, code: '56', isoCode: 'vi' },
  { name: LanguageName.Welsh, code: '57', isoCode: 'cy' }
];